### ISSUE TITLE
Crash when scroll table quickly

### ISSUE THREAD

**Issue by VladPodvoiskyi77** [dimaswisodewo/hacker-news-app#2]
<img width="809" alt="Screenshot 2023-02-14 at 17 44 24" src="https://user-images.githubusercontent.com/67429828/218801991-26fa6252-3960-4c5e-b661-e168fabdd0ef.png">

**Comment by dimaswisodewo** [comment]
Thank you for opening this issue! I will fix it soon!

**Comment by VladPodvoiskyi77** [comment]
Thank you for the great tutorial!

**Comment by dimaswisodewo** [comment]
Hi, I already fixed the problem. You can check the changes in this commit:
https://github.com/dimaswisodewo/hacker-news-app/commit/dd822585539b2a2e0589749e41cdc3cd0fe5b3ed?diff=split

You can check it if you have time. I hope this solves the problem! :)
