### ISSUE TITLE
This method should not be called on the main thread as it may lead to UI unresponsiveness.

### ISSUE THREAD

**Issue by VladPodvoiskyi77** [dimaswisodewo/hacker-news-app#3]
maybe better to use this -  @UIApplicationMain?
<img width="809" alt="Screenshot 2023-02-14 at 17 46 22" src="https://user-images.githubusercontent.com/67429828/218804431-3c35e3b1-6b95-489f-9ccc-25a88d615420.png">

**Comment by dimaswisodewo** [comment]
It looks like a bug by Apple. You can check the discussion here:
https://developer.apple.com/forums/thread/712074
and here:
https://developer.apple.com/forums/thread/714467?answerId=734799022#734799022
